@startuml myimage.svg
@startwire{myimage.svg}
move(0, 20)
* Host_App
    print("\n(test_sample.exe)")
--
move(120, 0)
* PCIe_Emulation #LightGrey
    * BRD #White
        print("\n(pcie-emu.ko)")
    --
    move(50, 0)
    * Proxy #White
        print("\n(proxy.exe)")
--
move(70, 0)
* Simulator_Model
    * Adapter [50x100]
        print("\nHost\nAdapter\nModel")
    --
    * Runtime_Model [100x100]
        move(5,0)
        * M1 [25x25]
        * M2 [25x25]
        --
        * M3 [25x25]
        * M4 [25x25]

Host_App(100%,15%) <=> PCIe_Emulation.BRD : [[ pcie_mapping.html#lblResource0 /dev/rescource0 ]]
Host_App <=> PCIe_Emulation.BRD : [[ pcie_mapping.html#lblResource2 /dev/rescource2 ]]
Host_App <=> PCIe_Emulation.BRD : [[ pcie_mapping.html#lblResource4 /dev/rescource4 ]]

PCIe_Emulation.BRD(100%,20%) <=> PCIe_Emulation.Proxy : BAR0
PCIe_Emulation.BRD <=> PCIe_Emulation.Proxy : BAR2
PCIe_Emulation.BRD <=> PCIe_Emulation.Proxy : BAR4

PCIe_Emulation.Proxy(100%,50%) <-> Simulator_Model : TCP\n  IP
Simulator_Model.Adapter(100%,50%) <-> Simulator_Model.Runtime_Model
@endwire
@enduml
